version: 2.1
orbs:
  codecov: codecov/codecov@1.0.3
machine:
  environment:
    JAVA_TOOL_OPTIONS: -javaagent:"~/.ivy2/cache/com.github.jbellis/jamm/jars/jamm-0.3.3.jar"
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run: sbt test:compile
      - save_cache:
          paths: [ "~/.m2", "~/.ivy2", "~/.cache/coursier" ]
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run: sbt clean coverage test coverageReport
      - codecov/upload:
          file: /home/circleci/project/target/scala-2.12/scoverage-report/scoverage.xml